### ISSUE TITLE
How to save net

### ISSUE THREAD

**Issue by Achillesy** [oliverchampion/IVIMNET#2]
```
def learn_IVIM(X_train, bvalues, arg, net=None):
param net: an optional input pre-trained network with initialized weights for e.g. transfer learning or warm start
```
I am a bit confused about the learning_IVIM function. Each execution of Example takes a lot of time to generate net.

- I want to know if you have a trained net data that I can download and use? 
- Or, I can save the training results for later use.
- Another thing I don’t know is, should the data used for training come from simulated data or patients data? 
- Can you provide an example of applying the trained net to actual patients?
 
Thanks.

**Comment by oliverchampion** [comment]
Hey!

Thanks for your comments! 
1: What do you mean exactly with "long"? On my regular desktop CPU it takes roughly 5 minutes to train the network. We hadn't uploaded a trained network as it only took 5 minutes to train. However, from your comments, I am assuming yours is taking considerably longer? In that case, I think we should solve that issue first... Howmany iterations is the network performing per second (will be printed in the terminal when the percentage bars are appearing)? Are you running it via CUDA or on the CPU? (to test on purely CPU you could change line 40 from hyperparams.py to self.device = "cpu") 

2: You can find more on saving and loading networks at https://pytorch.org/tutorials/beginner/saving_loading_models.html. We used to save the networks after performing net=learn_IVIM --> run torch.save(net,"path.pt") and load by running net=torch.load("path.pt"). Although I believe you can also just save the state_dict.

3: This depends. The network is unsupervised, so it can train directly on the data you want to ultimately use it for. So if you are evaluating it in simulations, then train towards simulated data. Otherwise, train it on real data.

4: Yes, Example_3_volunteer.py will run and apply it on a real volunteer dataset. 

Hope this helps! Let me know if you get stuck!

**Comment by Achillesy** [comment]
Thank you for your reply.

I think the key issue is that I am stuck on line 344 of deep.py.
```
final_model = copy.deepcopy(net.state_dict())
```
Yesterday I tried to reduce the epoch range from 1000 to 10, and I got the result about an hour later.

My computer is HP Z4G4. My operating system is Ubuntu 18.04. I created the ivim environment by running yum.
```
(ivim) achilles@HP-Z4-G4:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
(ivim) achilles@HP-Z4-G4:~$ pip show torch
Name: torch
Version: 1.4.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /miniconda3/envs/ivim/lib/python3.6/site-packages
Requires: 
Required-by: torchvision
(ivim) achilles@HP-Z4-G4:~$ python
Python 3.6.12 | packaged by conda-forge | (default, Dec  9 2020, 00:36:02) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> 
```

**Comment by Achillesy** [comment]
supplement:

I tested on pure CPU, it works much faster than GPU. But still took more than one minute to run 10 epochs.

**Comment by Achillesy** [comment]
```
            # final_model = copy.deepcopy(net.state_dict())
            final_model = [w for w in net.state_dict()] # Achilles
```
I solved this problem by replacing the deepcopy. I am not sure if this will cause other problems. If you have any ideas, please let me know.
Thank you.

**Comment by oliverchampion** [comment]
Hey Achillesy,

1: The line 344 allows you to load the "best performing network" at the end of your training. It should be fairly fast, but maybe there is a memory issue...? The deep.copy is there as otherwise the final_model will only be a pointer to the net.state_dict and contain the new iterations too, if I understood it correctly. Note that you probably can also remove the "save best model" option, in that case you will still have a really good model (10 patience after the "best"). 
2: Note that the network has early stopping in it, so if you put it to 500 epochs, it probably will only run ~50-100 epochs, so if 10 epochs takes 1 minute, your total training will be 5-10 minutes. This should be acceptable?

Also, when we perform it in patients, I ussually load all patients first, and put all patient through a single network (so it trains on all patients) and evaluate it on all patients. In this case, fitting for ALL patients will cost as long as it cost to fit for a single patient :). So 5-10 minutes. We built in a counter that allows max 500 batches per epoch to make sure performance is monitored regularly, 10 epochs will again only last 1 minute.

Hope this helps! Happy to help if you run in to anything else (or if your results are worse then ours; would also be itneresting! We only tested this in our own data).

May I ask what you are working on and planning to use the network for?

Cheers!

Oliver
